runtime: nodejs18
instance_class: B2  # Manual instance for long-running apps

manual_scaling:
  instances: 1  # Keeps the bot running

env_variables:
  DISCORD_TOKEN: "your_discord_token"
  #DISCORD_TOKEN: "invalid_token_will_pause_the_traffic"

entrypoint: node index.js
